### ISSUE TITLE
maven build problem. could not resolve dependency

### ISSUE THREAD

**Issue by Aehrraid** [ontometrics/slack-youtrack#13]
Hello. I tried building this plugin using following command:

 mvn -DYOUTRACK_USERNAME=bot -DYOUTRACK_PASSWORD=PW -DSLACK_WEBHOOKPATH=services/xxx/xxx/xxx -DYOUTRACK_URL=http://xxx:8081/ -DISSUE_HISTORY_WINDOW=10 -DDEFAULT_SLACK_CHANNEL=#tracker package

I receive the following maven error:

Failed to execute goal on project slack-youtrack: Could not resolve dependencies for project com.ontometrics.integrations:slack-youtrack:war:1.1-SNAPSHOT: The following artifacts could not be resolved: jetbrains:hub-client-util:jar:1.0.0, jetbrains:hub.api:jar:1.0.0, jetbrains:hub.api-impl:jar:1.0.0, jetbrains:hub.api.remote:jar:1.0.0, jetbrains:hub.client:jar:1.0.0: Could not find artifact jetbrains:hub-client-util:jar:1.0.0 in ontometrics (http://ontoserver.ontometrics.com:8081/nexus/content/groups/ontorepogroup)

The command  "mvn clean install -U" did not solve the problems.

Your nexus seems to be offline. Can you help me?

**Comment by Aehrraid** [comment]
I could build it using the libraries from JetBrains-Hub after including them to my local maven-repository.

can be closed.

**Comment by codeslubber** [comment]
Thanks
