### ISSUE TITLE
Cannot authenticate using credentials mode

### ISSUE THREAD

**Issue by yuvalbl** [ontometrics/slack-youtrack#15]
Hello

I could not authenticate using AUTH_TYPE=credentials 

For building the wor file I've used maven console with the following:
(real credencials and urls were edited, the rest is real data)

mvn -DYOUTRACK_USERNAME=MY_USER_NAME -DYOUTRACK_PASSWORD=MY_PASSWORD -DSLACK_WEBHOOK_PATH=services/T04D9APSK/B1E80FYG5/oKyPkzu7DvNHa83g5dz6qqby -DAPP_DATA_DIR=/opt/slack-youtrack -DYOUTRACK_URL=http://1.1.1.1:8080 -DYOUTRACK_HOST=http://1.1.1.1:8080 -DISSUE_HISTORY_WINDOW=10 -DDEFAULT_SLACK_CHANNEL=testy package

we currently using HTTP and not HTTPS for our youtrack service, in case it can be problematic

Server Log
![slack2youtrack_issue](https://cloud.githubusercontent.com/assets/11487010/16040079/3905cc9a-3236-11e6-88f0-fbeb90d99658.png)

**Comment by jrand0m** [comment]
Hi, i've done the fix if you're still interested.

**Comment by codeslubber** [comment]
Sure. Definitely.

**Comment by jrand0m** [comment]
made a pull request #16 with changes.
