### ISSUE TITLE
Where is target folder for deployment?

### ISSUE THREAD

**Issue by evil-shrike** [ontometrics/slack-youtrack#8]
> Drop war file into servlet container "webapps" directory

Could you clarify where is "webapps"  directory located in YouTrack?  It's not tomcat so it's unclear for me where to put built war file.
Thanks.

**Comment by Samhane** [comment]
I think you need to install tomcat and move war file into folder like 
`/var/lib/tomcat7/webapps/`

**Comment by evil-shrike** [comment]
got it. Sorry I thought it's a kind of plugin which should be place inside YT. Understood.
